version: "3"
services:
  bun:
    image: rahat3062/bun
    ports:
      - 80:80
    volumes:
      #Must be changed depending on the volume
      - C:\Users\edwin\Documents\GitHub\To-Do-Application\express-server:/app
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
