version: "3"
services:
  bun:
    image: rahat3062/bun
    ports:
      - 80:8000
    volumes:
      - /home/rahat/Desktop/To-Do-Application/express-server:/app
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
